In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
df.shape

(100, 6)

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
x=df.drop(columns=['has_covid'])      ### input data
x

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [ ]:
y=df['has_covid']      # Target output data
y

0      No
1     Yes
2      No
3      No
4      No
     ...
95     No
96    Yes
97     No
98     No
99    Yes
Name: has_covid, Length: 100, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train ,x_test ,y_train ,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
print("Total data shape:" ,df.shape)
print("___________________")
print("Input data shape:", x.shape)
print("x_train shape:",x_train.shape)
print("_________________________")
print("Target data shape",y.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

Total data shape: (100, 6)
___________________
Input data shape: (100, 5)
x_train shape: (80, 5)
_________________________
Target data shape (100,)
y_train shape: (80,)
y_test shape: (20,)

In [ ]:
df=pd.read_csv("/content/placement - placement (1).csv")
df.head(3)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [ ]:
df.shape

(100, 3)

In [ ]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [ ]:
x=df.drop(columns=['placed'])      ### input data
x

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

In [ ]:
y=df['placed']
y

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64

In [ ]:
print("Total data shape:" ,df.shape)
print("___________________")
print("Input data shape:", x.shape)
print("x_train shape:",x_train.shape)
print("_________________________")
print("Target data shape",y.shape)
print("y_train shape:",y_train.shape)
print("y_test shape:",y_test.shape)

Total data shape: (100, 3)
___________________
Input data shape: (100, 2)
x_train shape: (80, 5)
_________________________
Target data shape (100,)
y_train shape: (80,)
y_test shape: (20,)