In [ ]:
import pandas as pd

In [ ]:
# student_id, student_name, course_name, course_duration, total_fees
# insert 10 rows into dataframe
# convert this into csv and excel
# then create a repo ('Data_students') and upload datasets on this github

In [ ]:
student ={
    'Student_id' : [1,2,3,4,5,6,7,8,9,10],
    'Student_name' : ['DIvyansh', 'Rishi', 'Vikash', 'Akanksha', 'Sandeep', 'Abhishek', 'Sourbh', 'Tushar', 'Prachi', 'Ayushi'],
    'Course_name': ['Data Engineering','Data Analyst','Machine Learning','AI','Python','Power BI','SQL','Deep Learning','Tableau','Data Engineering'],
    'Course_duration': ['6 months','4 months','6 months','8 months','3 months','2 months','2 months','7 months','2 months','6 months'    ],
    'Total_fees': [50000,40000,60000,70000,20000,15000,12000,65000,18000,55000]
}

In [ ]:
df = pd.DataFrame(student)

In [ ]:
df

   Student_id Student_name       Course_name Course_duration  Total_fees
0           1     DIvyansh  Data Engineering        6 months       50000
1           2        Rishi      Data Analyst        4 months       40000
2           3       Vikash  Machine Learning        6 months       60000
3           4     Akanksha                AI        8 months       70000
4           5      Sandeep            Python        3 months       20000
5           6     Abhishek          Power BI        2 months       15000
6           7       Sourbh               SQL        2 months       12000
7           8       Tushar     Deep Learning        7 months       65000
8           9       Prachi           Tableau        2 months       18000
9          10       Ayushi  Data Engineering        6 months       55000

In [ ]:
df.to_csv('Student_data.csv')

In [ ]:
df.to_excel('Student_data.xlsx')

df

   Student_id Student_name       Course_name Course_duration  Total_fees
0           1     DIvyansh  Data Engineering        6 months       50000
1           2        Rishi      Data Analyst        4 months       40000
2           3       Vikash  Machine Learning        6 months       60000
3           4     Akanksha                AI        8 months       70000
4           5      Sandeep            Python        3 months       20000
5           6     Abhishek          Power BI        2 months       15000
6           7       Sourbh               SQL        2 months       12000
7           8       Tushar     Deep Learning        7 months       65000
8           9       Prachi           Tableau        2 months       18000
9          10       Ayushi  Data Engineering        6 months       55000

In [ ]:
pd.read_csv('Student_data.csv')

,Unnamed: 0,Student_id,Student_name,Course_name,Course_duration,Total_fees
0,0,1,Abhishek,Data Science,6 months,50000
1,1,2,Rishi,Data Analyst,4 months,40000
2,2,3,Vikash,Machine Learning,6 months,60000
3,3,4,Akanksha,AI,8 months,70000
4,4,5,Sandeep,Python,3 months,20000
5,5,6,Divyansh,Power BI,2 months,15000
6,6,7,Sourbh,SQL,2 months,12000
7,7,8,Tushar,Deep Learning,7 months,65000
8,8,9,Prachi,Tableau,2 months,18000
9,9,10,Ayushi,Data Engineering,6 months,55000