In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/placement - placement (1).csv")
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [ ]:
df['cgpa']=df['cgpa'].astype(int)
df

    cgpa  resume_score  placed
0     18          6.52       1
1     16          5.17       0
2     18          8.86       1
3     16          7.27       1
4     17          7.30       1
..   ...           ...     ...
95    16          6.38       0
96    18          7.76       1
97    16          7.78       0
98    18          5.63       1
99    16          6.61       0

[100 rows x 3 columns]

In [ ]:
df['cgpa']=df['cgpa']+10
df

    cgpa  resume_score  placed
0     28          6.52       1
1     26          5.17       0
2     28          8.86       1
3     26          7.27       1
4     27          7.30       1
..   ...           ...     ...
95    26          6.38       0
96    28          7.76       1
97    26          7.78       0
98    28          5.63       1
99    26          6.61       0

[100 rows x 3 columns]

In [ ]:
r=df['cgpa'].mean()
r

np.float64(26.47)

In [ ]:
s=df['cgpa'].median()
s

26.0

In [ ]:
g=df.filter(items=['cgpa','placed'])
g

    cgpa  placed
0     28       1
1     26       0
2     28       1
3     26       1
4     27       1
..   ...     ...
95    26       0
96    28       1
97    26       0
98    28       1
99    26       0

[100 rows x 2 columns]

In [ ]:
s=df.filter(items=[5,6],axis=0)  ## axis =0 means row wise operation
s

   cgpa  resume_score  placed
5    28          6.19       1
6    25          7.09       0

In [ ]:
s=df.to_dict()
s                         # save in dict

{'cgpa': {0: 28,
  1: 26,
  2: 28,
  3: 26,
  4: 27,
  5: 28,
  6: 25,
  7: 26,
  8: 26,
  9: 27,
  10: 26,
  11: 25,
  12: 26,
  13: 28,
  14: 27,
  15: 28,
  16: 28,
  17: 27,
  18: 25,
  19: 26,
  20: 25,
  21: 26,
  22: 26,
  23: 26,
  24: 28,
  25: 27,
  26: 26,
  27: 25,
  28: 27,
  29: 26,
  30: 27,
  31: 25,
  32: 25,
  33: 28,
  34: 28,
  35: 28,
  36: 28,
  37: 29,
  38: 26,
  39: 27,
  40: 28,
  41: 28,
  42: 26,
  43: 28,
  44: 25,
  45: 28,
  46: 25,
  47: 27,
  48: 25,
  49: 25,
  50: 28,
  51: 26,
  52: 25,
  53: 26,
  54: 25,
  55: 26,
  56: 26,
  57: 26,
  58: 26,
  59: 25,
  60: 25,
  61: 26,
  62: 25,
  63: 28,
  64: 27,
  65: 26,
  66: 28,
  67: 26,
  68: 26,
  69: 28,
  70: 27,
  71: 27,
  72: 27,
  73: 25,
  74: 25,
  75: 26,
  76: 29,
  77: 25,
  78: 25,
  79: 25,
  80: 27,
  81: 26,
  82: 27,
  83: 27,
  84: 25,
  85: 26,
  86: 26,
  87: 25,
  88: 28,
  89: 25,
  90: 25,
  91: 28,
  92: 25,
  93: 29,
  94: 28,
  95: 26,
  96: 28,
  97: 26,
  98: 28,
  99: 26},
 'resume_score': {0: 6.52,
  1: 5.17,
  2: 8.86,
  3: 7.27,
  4: 7.3,
  5: 6.19,
  6: 7.09,
  7: 6.29,
  8: 6.71,
  9: 7.12,
  10: 6.35,
  11: 6.54,
  12: 7.01,
  13: 5.09,
  14: 6.25,
  15: 5.93,
  16: 7.64,
  17: 8.71,
  18: 5.88,
  19: 8.11,
  20: 8.06,
  21: 7.64,
  22: 5.77,
  23: 7.13,
  24: 6.18,
  25: 5.68,
  26: 6.47,
  27: 6.15,
  28: 7.67,
  29: 7.3,
  30: 7.15,
  31: 7.02,
  32: 7.96,
  33: 7.73,
  34: 7.19,
  35: 7.48,
  36: 7.56,
  37: 8.21,
  38: 8.72,
  39: 6.19,
  40: 5.32,
  41: 5.15,
  42: 6.91,
  43: 7.95,
  44: 5.92,
  45: 5.44,
  46: 5.21,
  47: 8.14,
  48: 6.57,
  49: 6.73,
  50: 6.74,
  51: 7.39,
  52: 7.5,
  53: 7.16,
  54: 7.18,
  55: 6.87,
  56: 6.43,
  57: 7.21,
  58: 7.37,
  59: 7.57,
  60: 6.64,
  61: 7.96,
  62: 8.43,
  63: 7.58,
  64: 8.09,
  65: 8.75,
  66: 8.02,
  67: 6.81,
  68: 7.49,
  69: 9.06,
  70: 7.41,
  71: 8.22,
  72: 7.98,
  73: 6.48,
  74: 7.36,
  75: 7.94,
  76: 5.5,
  77: 6.92,
  78: 5.66,
  79: 7.28,
  80: 7.7,
  81: 6.72,
  82: 6.06,
  83: 8.08,
  84: 6.49,
  85: 5.46,
  86: 5.76,
  87: 5.05,
  88: 6.07,
  89: 7.49,
  90: 5.56,
  91: 6.3,
  92: 6.18,
  93: 7.39,
  94: 4.95,
  95: 6.38,
  96: 7.76,
  97: 7.78,
  98: 5.63,
  99: 6.61},
 'placed': {0: 1,
  1: 0,
  2: 1,
  3: 1,
  4: 1,
  5: 1,
  6: 0,
  7: 0,
  8: 0,
  9: 1,
  10: 0,
  11: 0,
  12: 0,
  13: 1,
  14: 1,
  15: 1,
  16: 1,
  17: 1,
  18: 0,
  19: 1,
  20: 0,
  21: 0,
  22: 0,
  23: 0,
  24: 1,
  25: 1,
  26: 0,
  27: 0,
  28: 1,
  29: 0,
  30: 1,
  31: 0,
  32: 0,
  33: 1,
  34: 1,
  35: 1,
  36: 1,
  37: 1,
  38: 0,
  39: 1,
  40: 1,
  41: 1,
  42: 1,
  43: 1,
  44: 0,
  45: 1,
  46: 0,
  47: 1,
  48: 0,
  49: 0,
  50: 1,
  51: 0,
  52: 0,
  53: 0,
  54: 0,
  55: 1,
  56: 0,
  57: 0,
  58: 0,
  59: 0,
  60: 0,
  61: 1,
  62: 0,
  63: 1,
  64: 1,
  65: 0,
  66: 1,
  67: 1,
  68: 0,
  69: 1,
  70: 1,
  71: 1,
  72: 1,
  73: 0,
  74: 0,
  75: 1,
  76: 1,
  77: 0,
  78: 0,
  79: 0,
  80: 1,
  81: 0,
  82: 1,
  83: 1,
  84: 0,
  85: 0,
  86: 0,
  87: 0,
  88: 1,
  89: 0,
  90: 0,
  91: 1,
  92: 0,
  93: 1,
  94: 1,
  95: 0,
  96: 1,
  97: 0,
  98: 1,
  99: 0}}

In [ ]:
q=df.to_string()    # save as string
q

'    cgpa  resume_score  placed\n0     28          6.52       1\n1     26          5.17       0\n2     28          8.86       1\n3     26          7.27       1\n4     27          7.30       1\n5     28          6.19       1\n6     25          7.09       0\n7     26          6.29       0\n8     26          6.71       0\n9     27          7.12       1\n10    26          6.35       0\n11    25          6.54       0\n12    26          7.01       0\n13    28          5.09       1\n14    27          6.25       1\n15    28          5.93       1\n16    28          7.64       1\n17    27          8.71       1\n18    25          5.88       0\n19    26          8.11       1\n20    25          8.06       0\n21    26          7.64       0\n22    26          5.77       0\n23    26          7.13       0\n24    28          6.18       1\n25    27          5.68       1\n26    26          6.47       0\n27    25          6.15       0\n28    27          7.67       1\n29    26          7.30       0\n30    27          7.15       1\n31    25          7.02       0\n32    25          7.96       0\n33    28          7.73       1\n34    28          7.19       1\n35    28          7.48       1\n36    28          7.56       1\n37    29          8.21       1\n38    26          8.72       0\n39    27          6.19       1\n40    28          5.32       1\n41    28          5.15       1\n42    26          6.91       1\n43    28          7.95       1\n44    25          5.92       0\n45    28          5.44       1\n46    25          5.21       0\n47    27          8.14       1\n48    25          6.57       0\n49    25          6.73       0\n50    28          6.74       1\n51    26          7.39       0\n52    25          7.50       0\n53    26          7.16       0\n54    25          7.18       0\n55    26          6.87       1\n56    26          6.43       0\n57    26          7.21       0\n58    26          7.37       0\n59    25          7.57       0\n60    25          6.64       0\n61    26          7.96       1\n62    25          8.43       0\n63    28          7.58       1\n64    27          8.09       1\n65    26          8.75       0\n66    28          8.02       1\n67    26          6.81       1\n68    26          7.49       0\n69    28          9.06       1\n70    27          7.41       1\n71    27          8.22       1\n72    27          7.98       1\n73    25          6.48       0\n74    25          7.36       0\n75    26          7.94       1\n76    29          5.50       1\n77    25          6.92       0\n78    25          5.66       0\n79    25          7.28       0\n80    27          7.70       1\n81    26          6.72       0\n82    27          6.06       1\n83    27          8.08       1\n84    25          6.49       0\n85    26          5.46       0\n86    26          5.76       0\n87    25          5.05       0\n88    28          6.07       1\n89    25          7.49       0\n90    25          5.56       0\n91    28          6.30       1\n92    25          6.18       0\n93    29          7.39       1\n94    28          4.95       1\n95    26          6.38       0\n96    28          7.76       1\n97    26          7.78       0\n98    28          5.63       1\n99    26          6.61       0'

In [ ]:
e=df.to_csv("/content/placement - placement (1).csv")
e

In [ ]:
idx=df.columns
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [ ]:
label=df.columns[0]     # first column lable
label

'cgpa'

In [ ]:
p=df.rename(columns= {'cgpa':'updated_cgpa','resume_score ':'semester_marks'})
p

    updated_cgpa  resume_score  placed
0             28          6.52       1
1             26          5.17       0
2             28          8.86       1
3             26          7.27       1
4             27          7.30       1
..           ...           ...     ...
95            26          6.38       0
96            28          7.76       1
97            26          7.78       0
98            28          5.63       1
99            26          6.61       0

[100 rows x 3 columns]

In [ ]:
# df['half']=df['cgpa'].where(df['cgpa']>7, other=0)
# df.head(10)

df['half']=df['resume_score'].where(df['resume_score']>7, other=0)
df.head(10)

   cgpa  resume_score  placed  half
0    28          6.52       1  0.00
1    26          5.17       0  0.00
2    28          8.86       1  8.86
3    26          7.27       1  7.27
4    27          7.30       1  7.30
5    28          6.19       1  0.00
6    25          7.09       0  7.09
7    26          6.29       0  0.00
8    26          6.71       0  0.00
9    27          7.12       1  7.12

In [ ]:
#row=11 to 13
# column=3
# 2 column rename
# new column name -- male customer

In [ ]:
df=pd.read_csv("/content/tips - tips (1).csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df.iloc[11:14]

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4

In [ ]:
r=df.rename(columns={'total_bill':'total_amount','tip':'add_tip'})
r

     total_amount  add_tip     sex smoker   day    time  size
0           16.99     1.01  Female     No   Sun  Dinner     2
1           10.34     1.66    Male     No   Sun  Dinner     3
2           21.01     3.50    Male     No   Sun  Dinner     3
3           23.68     3.31    Male     No   Sun  Dinner     2
4           24.59     3.61  Female     No   Sun  Dinner     4
..            ...      ...     ...    ...   ...     ...   ...
239         29.03     5.92    Male     No   Sat  Dinner     3
240         27.18     2.00  Female    Yes   Sat  Dinner     2
241         22.67     2.00    Male    Yes   Sat  Dinner     2
242         17.82     1.75    Male     No   Sat  Dinner     2
243         18.78     3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df['total_bill']=df['total_bill'].astype(int)
df

     total_bill   tip     sex smoker   day    time  size
0            16  1.01  Female     No   Sun  Dinner     2
1            10  1.66    Male     No   Sun  Dinner     3
2            21  3.50    Male     No   Sun  Dinner     3
3            23  3.31    Male     No   Sun  Dinner     2
4            24  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239          29  5.92    Male     No   Sat  Dinner     3
240          27  2.00  Female    Yes   Sat  Dinner     2
241          22  2.00    Male    Yes   Sat  Dinner     2
242          17  1.75    Male     No   Sat  Dinner     2
243          18  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df['Male_customers']=df['sex'].where(df['sex']=='Male', other=0)
df['Male_customers'].replace('Male',1,inplace=True)
df

/tmp/ipykernel_354/1855916827.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Male_customers'].replace('Male',1,inplace=True)
/tmp/ipykernel_354/1855916827.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Male_customers'].replace('Male',1,inplace=True)

     total_bill   tip     sex smoker   day    time  size  Male_customers
0            16  1.01  Female     No   Sun  Dinner     2               0
1            10  1.66    Male     No   Sun  Dinner     3               1
2            21  3.50    Male     No   Sun  Dinner     3               1
3            23  3.31    Male     No   Sun  Dinner     2               1
4            24  3.61  Female     No   Sun  Dinner     4               0
..          ...   ...     ...    ...   ...     ...   ...             ...
239          29  5.92    Male     No   Sat  Dinner     3               1
240          27  2.00  Female    Yes   Sat  Dinner     2               0
241          22  2.00    Male    Yes   Sat  Dinner     2               1
242          17  1.75    Male     No   Sat  Dinner     2               1
243          18  3.00  Female     No  Thur  Dinner     2               0

[244 rows x 8 columns]